// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVhdD--MPMltE6o3O19_DYQYO6Gm9QIY',
    appId: '1:450852349768:web:d28f8ecbaff72a2d07b57d',
    messagingSenderId: '450852349768',
    projectId: 'aurahealth-4bddd',
    authDomain: 'aurahealth-4bddd.firebaseapp.com',
    storageBucket: 'aurahealth-4bddd.firebasestorage.app',
    measurementId: 'G-WHPTY36EKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxM2iRxS7FTQaUMR9OOS3aaY2N9QtUxg',
    appId: '1:450852349768:android:0350191be205a7f207b57d',
    messagingSenderId: '450852349768',
    projectId: 'aurahealth-4bddd',
    storageBucket: 'aurahealth-4bddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR40vmMLUvkmwwRTpb8JrwO7FRXLjUqwA',
    appId: '1:450852349768:ios:833643f976bde61607b57d',
    messagingSenderId: '450852349768',
    projectId: 'aurahealth-4bddd',
    storageBucket: 'aurahealth-4bddd.firebasestorage.app',
    iosBundleId: 'com.example.auraHeallth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR40vmMLUvkmwwRTpb8JrwO7FRXLjUqwA',
    appId: '1:450852349768:ios:833643f976bde61607b57d',
    messagingSenderId: '450852349768',
    projectId: 'aurahealth-4bddd',
    storageBucket: 'aurahealth-4bddd.firebasestorage.app',
    iosBundleId: 'com.example.auraHeallth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOVhdD--MPMltE6o3O19_DYQYO6Gm9QIY',
    appId: '1:450852349768:web:fbc4e13a14701ea907b57d',
    messagingSenderId: '450852349768',
    projectId: 'aurahealth-4bddd',
    authDomain: 'aurahealth-4bddd.firebaseapp.com',
    storageBucket: 'aurahealth-4bddd.firebasestorage.app',
    measurementId: 'G-S1DC5PLHB6',
  );
}
